name: yet-another-sub-web

services:
  bot:
    image: moefaq/yet-another-sub-web
    restart: always
    environment:
      TZ: Asia/Shanghai
      NEXT_PUBLIC_SHORTURL: https://suo.yt/
      NEXT_PUBLIC_BACKENDS: https://api.sh1nyan.fun/sub?
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - network

networks:
  network:
